
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
/**
 *
 * @author DanielFernandoCarden
 */
public class frm06 extends javax.swing.JFrame {

    /**
     * Creates new form frm06
     */
    public frm06() {
        System.out.println("Ingrese");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        txtNum3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bntCalcular = new javax.swing.JButton();
        ComBox = new javax.swing.JComboBox<>();
        jMostrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese Numero 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 200, 180, 20);

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese Numero 1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 120, 170, 25);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingrese Numero 3");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 270, 180, 25);

        txtNum2.setForeground(new java.awt.Color(0, 0, 0));
        txtNum2.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNum2);
        txtNum2.setBounds(30, 230, 140, 30);

        txtNum1.setForeground(new java.awt.Color(0, 0, 0));
        txtNum1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNum1KeyPressed(evt);
            }
        });
        jPanel1.add(txtNum1);
        txtNum1.setBounds(30, 150, 150, 30);

        txtNum3.setForeground(new java.awt.Color(0, 0, 0));
        txtNum3.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNum3);
        txtNum3.setBounds(30, 300, 140, 30);

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("N.Mayor-N.Medio-N.Menor");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 70, 270, 20);

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ejercicio 06");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 10, 160, 40);

        bntCalcular.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        bntCalcular.setForeground(new java.awt.Color(0, 0, 0));
        bntCalcular.setText("Calcular");
        bntCalcular.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bntCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(bntCalcular);
        bntCalcular.setBounds(290, 430, 100, 40);

        ComBox.setBackground(new java.awt.Color(255, 255, 255));
        ComBox.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        ComBox.setForeground(new java.awt.Color(0, 0, 0));
        ComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayor", "Medio", "Menor" }));
        jPanel1.add(ComBox);
        ComBox.setBounds(30, 350, 100, 30);

        jMostrar.setBackground(new java.awt.Color(255, 255, 255));
        jMostrar.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        jMostrar.setForeground(new java.awt.Color(0, 0, 0));
        jMostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMostrar.setOpaque(true);
        jPanel1.add(jMostrar);
        jMostrar.setBounds(20, 410, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/batman-rojo-y-negro-6294 (2).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, 0, 440, 500);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    public boolean isNumber(String numero) {

        try {
            int Number = Integer.parseInt(numero);
            return true;
        } catch (NumberFormatException NFE) {
            JOptionPane.showMessageDialog(this,
                    "El texto " + numero + " no es un numero valido",
                    "Numero Invalido", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    public  void Calcularnumero() {
        if ((isNumber(txtNum1.getText())) && (isNumber(txtNum2.getText())) && (isNumber(txtNum3.getText()))) {
            int num1 = Integer.parseInt(txtNum1.getText());
            int num2 = Integer.parseInt(txtNum2.getText());
            int num3 = Integer.parseInt(txtNum3.getText());

            String op = ComBox.getSelectedItem().toString();
            switch (op) {
                case "Mayor": {
                    if (num1 > num2 && num1 > num3) {
                        jMostrar.setText("numero mayor " + num1);
                    }
                }
                if (num2 > num1 && num2 > num3) {
                    jMostrar.setText("numero mayor " + num2);
                }
                if (num3 > num1 && num3 > num2) {
                    jMostrar.setText("numero mayor " + num3);
                }
                break;
                case "Medio":
                    if (num1 > num2) {
                        if (num1 < num3) {
                            jMostrar.setText("numero de en medio " + num1);
                        }
                    }
                    if (num1 > num3) {
                        if (num1 < num2) {
                            jMostrar.setText("numero de en medio " + num1);
                        }
                    }
                    if (num2 > num1) {
                        if (num2 < num3) {
                            jMostrar.setText("numero de en medio " + num2);
                        }
                    }
                    if (num2 > num3) {
                        if (num2 < num1) {
                            jMostrar.setText("numero de en medio " + num2);
                        }
                    }
                    if (num3 > num1) {
                        if (num3 < num2) {
                            jMostrar.setText("numero de en medio " + num3);
                        }
                    }
                    if (num3 > num2) {
                        if (num3 < num1) {
                            jMostrar.setText("numero menor " + num3);
                        }
                    }
                    break;
                case "Menor":
                    if (num1 < num2 && num1 < num3) {
                        jMostrar.setText("numero menor " + num1);
                    }
                    if (num2 < num1 && num2 < num3) {
                        jMostrar.setText("numero menor " + num2);
                    }
                    if (num3 < num1 && num3 < num2) {
                        jMostrar.setText("numero menor " + num3);
                    }
                    break;
                default:
                    jMostrar.setText("opcion ingresada invalida");
                    break;
            }
        }
    }


    private void bntCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularActionPerformed

        Calcularnumero();

    }//GEN-LAST:event_bntCalcularActionPerformed

    private void txtNum1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Calcularnumero();
        }
    }//GEN-LAST:event_txtNum1KeyPressed

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm06().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBox;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton bntCalcular;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jMostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtNum3;
    // End of variables declaration//GEN-END:variables

}
